//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.1
//     from Assets/Projects/SpellController/Inputs/SpellControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Projects/SpellController/Inputs/SpellControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @SpellControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @SpellControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SpellControls"",
    ""maps"": [
        {
            ""name"": ""ItemInputs"",
            ""id"": ""9b3b6ce9-4fa3-4e1b-b988-a410d31d093c"",
            ""actions"": [
                {
                    ""name"": ""ToggleInputs"",
                    ""type"": ""Button"",
                    ""id"": ""01f218e4-8246-4ff6-bed7-2c9e90c70f00"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootInputs"",
                    ""type"": ""Button"",
                    ""id"": ""10a255bf-79eb-43fd-884e-10891195f181"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""095411c3-4037-4462-92e9-af24caf302e3"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleInputs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6341f865-7302-4ef0-a2ba-d502952884b6"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleInputs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40120778-658e-48ca-ae84-c61fff317801"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleInputs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3796b621-352d-4a71-801b-7e53d43ac827"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleInputs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""370027f1-d2a2-45d9-a565-3f52557df321"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootInputs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2f58bd0-21d0-4137-8615-90f65ee73fbe"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootInputs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ItemInputs
        m_ItemInputs = asset.FindActionMap("ItemInputs", throwIfNotFound: true);
        m_ItemInputs_ToggleInputs = m_ItemInputs.FindAction("ToggleInputs", throwIfNotFound: true);
        m_ItemInputs_ShootInputs = m_ItemInputs.FindAction("ShootInputs", throwIfNotFound: true);
    }

    ~@SpellControls()
    {
        UnityEngine.Debug.Assert(!m_ItemInputs.enabled, "This will cause a leak and performance issues, SpellControls.ItemInputs.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ItemInputs
    private readonly InputActionMap m_ItemInputs;
    private List<IItemInputsActions> m_ItemInputsActionsCallbackInterfaces = new List<IItemInputsActions>();
    private readonly InputAction m_ItemInputs_ToggleInputs;
    private readonly InputAction m_ItemInputs_ShootInputs;
    /// <summary>
    /// Provides access to input actions defined in input action map "ItemInputs".
    /// </summary>
    public struct ItemInputsActions
    {
        private @SpellControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ItemInputsActions(@SpellControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ItemInputs/ToggleInputs".
        /// </summary>
        public InputAction @ToggleInputs => m_Wrapper.m_ItemInputs_ToggleInputs;
        /// <summary>
        /// Provides access to the underlying input action "ItemInputs/ShootInputs".
        /// </summary>
        public InputAction @ShootInputs => m_Wrapper.m_ItemInputs_ShootInputs;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ItemInputs; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ItemInputsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ItemInputsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ItemInputsActions" />
        public void AddCallbacks(IItemInputsActions instance)
        {
            if (instance == null || m_Wrapper.m_ItemInputsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ItemInputsActionsCallbackInterfaces.Add(instance);
            @ToggleInputs.started += instance.OnToggleInputs;
            @ToggleInputs.performed += instance.OnToggleInputs;
            @ToggleInputs.canceled += instance.OnToggleInputs;
            @ShootInputs.started += instance.OnShootInputs;
            @ShootInputs.performed += instance.OnShootInputs;
            @ShootInputs.canceled += instance.OnShootInputs;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ItemInputsActions" />
        private void UnregisterCallbacks(IItemInputsActions instance)
        {
            @ToggleInputs.started -= instance.OnToggleInputs;
            @ToggleInputs.performed -= instance.OnToggleInputs;
            @ToggleInputs.canceled -= instance.OnToggleInputs;
            @ShootInputs.started -= instance.OnShootInputs;
            @ShootInputs.performed -= instance.OnShootInputs;
            @ShootInputs.canceled -= instance.OnShootInputs;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ItemInputsActions.UnregisterCallbacks(IItemInputsActions)" />.
        /// </summary>
        /// <seealso cref="ItemInputsActions.UnregisterCallbacks(IItemInputsActions)" />
        public void RemoveCallbacks(IItemInputsActions instance)
        {
            if (m_Wrapper.m_ItemInputsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ItemInputsActions.AddCallbacks(IItemInputsActions)" />
        /// <seealso cref="ItemInputsActions.RemoveCallbacks(IItemInputsActions)" />
        /// <seealso cref="ItemInputsActions.UnregisterCallbacks(IItemInputsActions)" />
        public void SetCallbacks(IItemInputsActions instance)
        {
            foreach (var item in m_Wrapper.m_ItemInputsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ItemInputsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ItemInputsActions" /> instance referencing this action map.
    /// </summary>
    public ItemInputsActions @ItemInputs => new ItemInputsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ItemInputs" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ItemInputsActions.AddCallbacks(IItemInputsActions)" />
    /// <seealso cref="ItemInputsActions.RemoveCallbacks(IItemInputsActions)" />
    public interface IItemInputsActions
    {
        /// <summary>
        /// Method invoked when associated input action "ToggleInputs" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleInputs(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ShootInputs" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShootInputs(InputAction.CallbackContext context);
    }
}
